easy_admin:
    design:
        menu:
            - {route: app_homepage, label: 'Home'}
            - {entity: Transcript}
            - {entity: User}
            - {entity: UserTranscript}

    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
#        - App\Entity\UserTranscript
        Transcript:
            class: App\Entity\Transcript
        UserTranscript:
            class: App\Entity\UserTranscript
        User:
            class: App\Entity\User
