<?php // generated by @SurvosLanding/MenuBuilder.php.twig

namespace App\Menu;

use Survos\LandingBundle\Menu\LandingMenuBuilder;

class MenuBuilder extends LandingMenuBuilder
{

    public function createMainMenu(array $options)
    {
        $menu = $this->factory->createItem('root');
$menu->setChildrenAttribute('class', 'nav navbar-nav mr-auto');

$menu->addChild('survos_landing', ['route' => 'survos_landing'])
->setAttribute('icon', 'fas fa-home');

    $menu->addChild('survos_landing_credits', ['route' => 'survos_landing_credits'])
->setAttribute('icon', 'fas fa-trophy');

        $menu->addChild('transcript_index', ['route' => 'transcript_index'])
            ->setAttribute('icon', 'fas fa-document-o');
        $menu->addChild('transcript_test', ['route' => 'test'])
            ->setAttribute('icon', 'fas fa-check');

        // $menu->addChild('admin', ['route' => 'easyadmin']);

// ... add more children

return $this->cleanupMenu($menu);
}



}